-- ============================================================================
-- TradeConnect — 001 SCHEMA
-- B2C marketplace connecting customers to verified tradespeople (Lae, PNG).
-- ============================================================================

-- gen_random_uuid() is built into Postgres 13+ (and pgcrypto is pre-installed
-- on Supabase), so no extension is required here.

-- ---------------------------------------------------------------------------
-- profiles: one row per auth user, created automatically by a trigger
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  user_id    uuid primary key references auth.users (id) on delete cascade,
  role       text not null default 'customer'
             check (role in ('customer', 'tradesperson', 'admin')),
  full_name  text not null default '',
  phone      text,
  city       text not null default 'Lae',
  created_at timestamptz not null default now()
);

comment on table public.profiles is 'Account profile + role for every authenticated user.';

-- ---------------------------------------------------------------------------
-- categories: pilot trades (Electrical, Mechanical, Plumbing)
-- ---------------------------------------------------------------------------
create table if not exists public.categories (
  id   int generated by default as identity primary key,
  name text not null unique,
  slug text not null unique
);

-- ---------------------------------------------------------------------------
-- tradesperson_profiles: extra data for role = 'tradesperson'
-- free_jobs_remaining drives the "first 3 jobs are commission free" rule.
-- ---------------------------------------------------------------------------
create table if not exists public.tradesperson_profiles (
  user_id             uuid primary key references public.profiles (user_id) on delete cascade,
  bio                 text not null default '',
  service_area        text not null default 'Lae',
  years_experience    int  not null default 0 check (years_experience >= 0),
  hourly_rate         numeric(12, 2) check (hourly_rate >= 0),
  verified_status     text not null default 'unverified'
                      check (verified_status in ('unverified', 'pending', 'verified', 'rejected')),
  free_jobs_remaining int  not null default 3 check (free_jobs_remaining >= 0),
  jobs_completed      int  not null default 0 check (jobs_completed >= 0),
  rating_avg          numeric(3, 2) not null default 0,
  rating_count        int  not null default 0,
  created_at          timestamptz not null default now()
);

comment on column public.tradesperson_profiles.free_jobs_remaining is
  'Commission-free completed jobs left for this tradesperson (starts at 3).';

-- ---------------------------------------------------------------------------
-- tradesperson_categories: many-to-many trades per tradesperson
-- ---------------------------------------------------------------------------
create table if not exists public.tradesperson_categories (
  user_id     uuid not null references public.tradesperson_profiles (user_id) on delete cascade,
  category_id int  not null references public.categories (id) on delete cascade,
  primary key (user_id, category_id)
);

-- ---------------------------------------------------------------------------
-- jobs
-- status: open -> assigned -> completed  (or cancelled)
-- ---------------------------------------------------------------------------
create table if not exists public.jobs (
  id                       uuid primary key default gen_random_uuid(),
  customer_id              uuid not null references public.profiles (user_id) on delete cascade,
  category_id              int  not null references public.categories (id),
  title                    text not null default '',
  description              text not null check (length(btrim(description)) > 0),
  location_text            text not null default 'Lae',
  photo_urls               text[] not null default '{}',
  status                   text not null default 'open'
                           check (status in ('open', 'assigned', 'completed', 'cancelled')),
  assigned_tradesperson_id uuid references public.profiles (user_id) on delete set null,
  estimated_value          numeric(12, 2) not null default 0 check (estimated_value >= 0),
  completed_at             timestamptz,
  created_at               timestamptz not null default now()
);

create index if not exists jobs_customer_idx  on public.jobs (customer_id, created_at desc);
create index if not exists jobs_assigned_idx  on public.jobs (assigned_tradesperson_id, created_at desc);
create index if not exists jobs_status_idx    on public.jobs (status, category_id, created_at desc);

-- ---------------------------------------------------------------------------
-- job_requests: both directions
--   customer_invite      -> customer asks a specific tradesperson
--   tradesperson_quote   -> tradesperson quotes on an open job (lead)
-- ---------------------------------------------------------------------------
create table if not exists public.job_requests (
  id              uuid primary key default gen_random_uuid(),
  job_id          uuid not null references public.jobs (id) on delete cascade,
  tradesperson_id uuid not null references public.profiles (user_id) on delete cascade,
  origin          text not null default 'tradesperson_quote'
                  check (origin in ('customer_invite', 'tradesperson_quote')),
  message         text not null default '',
  quoted_price    numeric(12, 2) check (quoted_price >= 0),
  status          text not null default 'pending'
                  check (status in ('pending', 'accepted', 'declined', 'withdrawn')),
  created_at      timestamptz not null default now(),
  unique (job_id, tradesperson_id)
);

create index if not exists job_requests_job_idx on public.job_requests (job_id, created_at desc);
create index if not exists job_requests_tp_idx  on public.job_requests (tradesperson_id, status, created_at desc);

-- ---------------------------------------------------------------------------
-- messages: in-job chat between the customer and the tradesperson
-- ---------------------------------------------------------------------------
create table if not exists public.messages (
  id          uuid primary key default gen_random_uuid(),
  job_id      uuid not null references public.jobs (id) on delete cascade,
  sender_id   uuid not null references public.profiles (user_id) on delete cascade,
  receiver_id uuid not null references public.profiles (user_id) on delete cascade,
  body        text not null check (length(btrim(body)) > 0),
  created_at  timestamptz not null default now()
);

create index if not exists messages_job_idx on public.messages (job_id, created_at);

-- ---------------------------------------------------------------------------
-- ratings: one review per job, only after completion (enforced by trigger)
-- ---------------------------------------------------------------------------
create table if not exists public.ratings (
  id              uuid primary key default gen_random_uuid(),
  job_id          uuid not null unique references public.jobs (id) on delete cascade,
  customer_id     uuid not null references public.profiles (user_id) on delete cascade,
  tradesperson_id uuid not null references public.profiles (user_id) on delete cascade,
  stars           int  not null check (stars between 1 and 5),
  review_text     text,
  created_at      timestamptz not null default now()
);

create index if not exists ratings_tp_idx on public.ratings (tradesperson_id, created_at desc);

-- ---------------------------------------------------------------------------
-- verifications: ID + certificate submitted for admin approval
-- ---------------------------------------------------------------------------
create table if not exists public.verifications (
  id              uuid primary key default gen_random_uuid(),
  tradesperson_id uuid not null references public.profiles (user_id) on delete cascade,
  id_doc_url      text not null,
  certificate_url text,
  status          text not null default 'pending'
                  check (status in ('pending', 'approved', 'rejected')),
  notes           text,
  reviewed_by     uuid references public.profiles (user_id),
  reviewed_at     timestamptz,
  created_at      timestamptz not null default now()
);

-- at most one open submission per tradesperson
create unique index if not exists verifications_one_pending_idx
  on public.verifications (tradesperson_id)
  where status = 'pending';

create index if not exists verifications_status_idx on public.verifications (status, created_at desc);

-- ---------------------------------------------------------------------------
-- commissions: 5% of job value, written by trigger on job completion
-- ---------------------------------------------------------------------------
create table if not exists public.commissions (
  id              uuid primary key default gen_random_uuid(),
  job_id          uuid not null unique references public.jobs (id) on delete cascade,
  tradesperson_id uuid not null references public.profiles (user_id) on delete cascade,
  job_value       numeric(12, 2) not null default 0,
  rate            numeric(5, 4) not null default 0.05,
  amount          numeric(12, 2) not null default 0,
  waived          boolean not null default false,
  status          text not null default 'pending'
                  check (status in ('pending', 'waived', 'paid', 'cancelled')),
  created_at      timestamptz not null default now()
);

create index if not exists commissions_tp_idx on public.commissions (tradesperson_id, created_at desc);
